//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJewelry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memo
    {
        public int Id { get; set; }
        public int PresenterID { get; set; }
        public Nullable<int> StyleID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Quantity { get; set; }
        public string Notes { get; set; }
    
        public virtual Presenter Presenter { get; set; }
        public virtual Style Style { get; set; }
    }
}
