//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJewelry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesLedger
    {
        public int Id { get; set; }
        public Nullable<int> StyleId { get; set; }
        public string StyleInfo { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Notes { get; set; }
        public Nullable<int> BuyerId { get; set; }
    
        public virtual Buyer Buyer { get; set; }
    }
}
