//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJewelry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Style
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Style()
        {
            this.Memos = new HashSet<Memo>();
            this.StyleComponents = new HashSet<StyleComponent>();
        }
    
        public int Id { get; set; }
        public string StyleNum { get; set; }
        public string StyleName { get; set; }
        public string Desc { get; set; }
        public Nullable<int> JewelryTypeId { get; set; }
        public int CollectionId { get; set; }
        public Nullable<decimal> MetalWeight { get; set; }
        public Nullable<System.DateTime> IntroDate { get; set; }
        public byte[] Image { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> ChainLength { get; set; }
        public Nullable<decimal> RetailRatio { get; set; }
        public Nullable<decimal> RedlineRatio { get; set; }
        public int Quantity { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual JewelryType JewelryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memo> Memos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StyleComponent> StyleComponents { get; set; }
    }
}
