//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJewelry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleComponent
    {
        public int Id { get; set; }
        public int StyleId { get; set; }
        public int ComponentId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Style Style { get; set; }
    }
}
