/*
Deployment script for OJewelryDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "OJewelryDB"
:setvar DefaultFilePrefix "OJewelryDB"


GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/

GO
USE [$(DatabaseName)];
GO

/* Styles-Casting */
PRINT N'Dropping [dbo].[FK_StyleCasting_ToStyles]...';
GO
/*ALTER TABLE [dbo].[StyleCastings] DROP CONSTRAINT [FK_StyleCasting_ToStyles];*/
ALTER TABLE [dbo].[StyleCastings] DROP CONSTRAINT [FK_StyleCasting_ToStyleId]
GO
PRINT N'Creating [dbo].[FK_StyleCasting_ToStyles]...';
GO
ALTER TABLE [dbo].[StyleCastings] WITH NOCHECK
    ADD CONSTRAINT [FK_StyleCasting_ToStyleId] FOREIGN KEY ([StyleId]) REFERENCES [dbo].[Styles] ([Id]) ON DELETE CASCADE;
GO
ALTER TABLE [dbo].[StyleCastings] WITH CHECK CHECK CONSTRAINT [FK_StyleCasting_ToStyleId];
GO
PRINT N'Update complete.';

/* Styles-Labor */
PRINT N'Dropping [dbo].[FK_StyleLabor_ToStyles]...';
GO
/* ALTER TABLE [dbo].[StyleLabor] DROP CONSTRAINT [FK_StyleLabor_ToMisc]; */
ALTER TABLE [dbo].[StyleLabor] DROP CONSTRAINT [FK_StyleLabor_ToStyles]; 
GO
PRINT N'Creating [dbo].[FK_StyleLabor_ToStyles]...';
GO
ALTER TABLE [dbo].[StyleLabor] WITH NOCHECK
    ADD CONSTRAINT [FK_StyleLabor_ToStyles] FOREIGN KEY ([StyleId]) REFERENCES [dbo].[Styles] ([Id]) ON DELETE CASCADE;
GO
ALTER TABLE [dbo].[StyleLabor] WITH CHECK CHECK CONSTRAINT [FK_StyleLabor_ToStyles];
GO
PRINT N'Update complete.';
GO

/* Styles-Misc */
PRINT N'Dropping [dbo].[FK_StyleMisc_ToStyles]...';
GO
ALTER TABLE [dbo].[StyleMisc] DROP CONSTRAINT [FK_StyleMisc_ToStyles];
GO
PRINT N'Creating [dbo].[FK_StyleMisc_ToStyles]...';
GO
ALTER TABLE [dbo].[StyleMisc] WITH NOCHECK
    ADD CONSTRAINT [FK_StyleMisc_ToStyles] FOREIGN KEY ([StyleId]) REFERENCES [dbo].[Styles] ([Id]) ON DELETE CASCADE;
GO
ALTER TABLE [dbo].[StyleMisc] WITH CHECK CHECK CONSTRAINT [FK_StyleMisc_ToStyles];
GO
PRINT N'Update complete.';
GO
