

/****** Object:  Database [OJewelryDBDeDev]    Script Date: 12/27/2017 5:58:22 PM ******/
/*
Manually create DB in each environment, the run script to build tables

CREATE DATABASE [OJewelryDBDeDev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OJewelryDBDeDev', FILENAME = N'C:\Users\Darryl\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\OJewelryDBDeDev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OJewelryDBDeDev_log', FILENAME = N'C:\Users\Darryl\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\OJewelryDBDeDev.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
*/
ALTER DATABASE [OJewelryDBDeDev] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OJewelryDBDeDev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OJewelryDBDeDev] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [OJewelryDBDeDev] SET ANSI_NULLS ON 
GO

ALTER DATABASE [OJewelryDBDeDev] SET ANSI_PADDING ON 
GO

ALTER DATABASE [OJewelryDBDeDev] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [OJewelryDBDeDev] SET ARITHABORT ON 
GO

ALTER DATABASE [OJewelryDBDeDev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OJewelryDBDeDev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [OJewelryDBDeDev] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [OJewelryDBDeDev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [OJewelryDBDeDev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OJewelryDBDeDev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OJewelryDBDeDev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET RECOVERY FULL 
GO

ALTER DATABASE [OJewelryDBDeDev] SET  MULTI_USER 
GO

ALTER DATABASE [OJewelryDBDeDev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OJewelryDBDeDev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OJewelryDBDeDev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OJewelryDBDeDev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OJewelryDBDeDev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OJewelryDBDeDev] SET QUERY_STORE = OFF
GO

USE [OJewelryDBDeDev]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [OJewelryDBDeDev] SET  READ_WRITE 
GO


