// <auto-generated />
namespace OJewelry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v11makepricemandatory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v11makepricemandatory));
        
        string IMigrationMetadata.Id
        {
            get { return "201808051253300_v1.1-make-price-mandatory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
