// <auto-generated />
namespace OJewelry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v61CascadeDeletes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v61CascadeDeletes));
        
        string IMigrationMetadata.Id
        {
            get { return "201804191525378_v.61-CascadeDeletes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
