// <auto-generated />
namespace OJewelry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v12MetalWt_deciml : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v12MetalWt_deciml));
        
        string IMigrationMetadata.Id
        {
            get { return "201808201548458_v1.2MetalWt_deciml"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
