// <auto-generated />
namespace OJewelry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v11_AddStonesShapesFindings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v11_AddStonesShapesFindings));
        
        string IMigrationMetadata.Id
        {
            get { return "201808041250151_v1.1_AddStones-Shapes-Findings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
