// <auto-generated />
namespace OJewelry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v652 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v652));
        
        string IMigrationMetadata.Id
        {
            get { return "201805260039404_v.652"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
