// <auto-generated />
namespace OJewelry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v12FindingsWeight194 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v12FindingsWeight194));
        
        string IMigrationMetadata.Id
        {
            get { return "201808141522050_v1.2FindingsWeight19.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
