// <auto-generated />
namespace OJewelry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    /*
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v11_AddStonesShapesFindings : IMigrationMetadata
    {
        private readonly ResourceManager Resources2 = new ResourceManager(typeof(v11_AddStonesShapesFindings));
        
        string IMigrationMetadata.Id2
        {
            get { return "201808042159223_v1.1_AddStones-Shapes-Findings"; }
        }
        
        string IMigrationMetadata.Source2
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target2
        {
            get { return Resources.GetString("Target"); }
        }
    }
    */
}
