// <auto-generated />
namespace OJewelry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v11addfindingweight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v11addfindingweight));
        
        string IMigrationMetadata.Id
        {
            get { return "201808051651266_v1.1-add-finding-weight"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
