// <auto-generated />
namespace OJewelry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v20AddVendorToLaborAndMisc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v20AddVendorToLaborAndMisc));
        
        string IMigrationMetadata.Id
        {
            get { return "201911010145387_v2.0AddVendorToLaborAndMisc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
