// <auto-generated />
namespace OJewelry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _17AddJTOption : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17AddJTOption));
        
        string IMigrationMetadata.Id
        {
            get { return "201906232056121_1.7AddJTOption"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
