// <auto-generated />
namespace OJewelry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v16ExtendStyleNumto25 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v16ExtendStyleNumto25));
        
        string IMigrationMetadata.Id
        {
            get { return "201903202354409_v1.6ExtendStyleNumto25"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
